url: "https://annagoss.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/ff-studio" # the subpath of your site, e.g. /blog
title: "FF studio" # the name of your site, e.g. ACME Corp.
